url: https://ryanormond.github.io
baseurl: /

# Site settings
title: R Ormond
email: your-email@domain.com
description: #write website description here
            "Personal portfolio website for Ryan Ormond, showcasing my work and achievements"


# Team names, titles and social links
people:
- name: Ryan Ormond
  pic: 2
  position: Software Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ryan-ormond/
    - title: github
      url: http://github.com/ryanormond

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ryan-ormond/
  - title: github
    url: http://github.com/ryanormond

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty
